import type { Metadata } from "next";
import { Itim } from 'next/font/google';
import "./globals.css";
import Provider from "./provider";

const MyAppFont = Itim({weight: "400",subsets:['latin']});

export const metadata: Metadata = {
  title: "Story Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={MyAppFont.className}
      >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
